version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - '80:8080'
    depends_on:
      - db
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=${USER}
      - DRUPAL_DATABASE_PASSWORD=${PASSWORD}
      - DRUPAL_DATABASE_NAME=${DATABASE}

db:
  image: bitnami/mariadb:latest
  environment:
    - MARIADB_USER=YAM428
    - MARIADB_PASSWORD=<30718054>
    - MARIADB_DATABASE=final
  volumes:
    - db_data:/bitnami

webserver:
  image: nginx
  ports:
    - '80:80'
    - '443:443'
  depends_on:
    - drupal
    
    volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf

certbot:
  image: certbot
  volumes:
    - '/etc/letsencrypt:/etc/letsencrypt'
    - '/var/lib/letsencrypt:/var/lib/letsencrypt'
  depends_on:
    - webserver
