worker_processes 1;

events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name edayalcin.me;
    
    location / {
      proxy_pass http://drupal:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
